apiVersion: v1
kind: ConfigMap
metadata: 
  name: db-config
  namespace: expense
  labels:
    project: expense
    app: backend
    tier: app
data:
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    app: backend
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      project: expense
      app: backend
      tier: app
  template:
    metadata:
      labels:
        project: expense
        app: backend
        tier: app
    spec:
      containers:
        - name: backend
          image: cekharch/backend:v11
          envFrom:
            - configMapRef:
                name: db-config
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
  labels:
    project: expense
    app: backend
    tier: app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    project: expense
    app: backend
    tier: app